development:
  AWS_ACCESS_KEY: AKIAIWCDFXHBPP6FZCIA
  AWS_SECRET_KEY: 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
  GMAIL_USERNAME: max@maxshermarketing.com
  GMAIL_PASSWORD: 2ue7JaKor4asPDAbo}jnLGPU%dc
  MAIL_RECIPIENT: doug@maxshermarketing.com
